CLOUDP-70059: mongocli ops-manager|cloud-manager backups config list|ls
mongodb/mongocli pull request #464
Opened 2020-09-28 08:48 UTC by andreaangiolillo

## Proposed changes

_Jira ticket:_ CLOUDP-70059

Closes #[issue number]

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

```
./bin/mongocli om backup config list -P ops -o json
{
  "links": [
    {
      "rel": "self",
      "href": "http://localhost:8080/api/public/v1.0/groups/5f6cc16511c3aa3a90b5ec34/backupConfigs?pageNum=1\u0026itemsPerPage=100"
    }
  ],
  "results": [
    {
      "groupId": "5f6cc16511c3aa3a90b5ec34",
      "clusterId": "5f6dfb3a11c3aa3a90b66db6",
      "statusName": "INACTIVE"
    },
    {
      "groupId": "5f6cc16511c3aa3a90b5ec34",
      "clusterId": "5f719b052845cb05726a860b",
      "statusName": "STARTED",
      "storageEngineName": "WIRED_TIGER"
    },
    {
      "groupId": "5f6cc16511c3aa3a90b5ec34",
      "clusterId": "5f719b352845cb05726a86f9",
      "statusName": "STARTED",
      "storageEngineName": "WIRED_TIGER"
    }
  ],
  "totalCount": 3
}
```
```

./bin/mongocli om backup config list -P ops
PROJECT ID                 CLUSTER ID                 STATUS     STORAGE ENGINE
5f6cc16511c3aa3a90b5ec34   5f6dfb3a11c3aa3a90b66db6   INACTIVE
5f6cc16511c3aa3a90b5ec34   5f719b052845cb05726a860b   STARTED    WIRED_TIGER
5f6cc16511c3aa3a90b5ec34   5f719b352845cb05726a86f9   STARTED    WIRED_TIGER
```

2020-09-28 08:48 UTC, andreaangiolillo commented
waiting https://github.com/mongodb/mongocli/pull/463

2020-09-28 09:04 UTC, andreaangiolillo commented
@gssbzn tagging you here so that you can review this PR once you're back

2020-09-29 08:31 UTC, gssbzn requested changes
happy to keep this instead of one for get one for list, couple of nits

2020-09-29 08:31 UTC, gssbzn commented on internal/store/backup_configs.go
> +	case config.OpsManagerService:
[nit] this should work for cloud manager as well, https://docs.cloudmanager.mongodb.com/reference/api/backup-configurations/

2020-09-29 08:31 UTC, gssbzn commented on internal/store/backup_configs.go
> +
[nit] extra space

2020-09-29 08:31 UTC, gssbzn commented on internal/cli/opsmanager/backup/config/describe_test.go
> +
extra space

2020-09-29 08:31 UTC, gssbzn commented on internal/cli/opsmanager/backup/config/describe.go
> +		Use:     "describe [clusterID]",
[nit] left this comment in a separate PR but if the id is mandatory then this should be 
```suggestion
		Use:     "describe <clusterID>",
```

2020-09-29 11:28 UTC, gssbzn approved these changes
LGTM

2020-09-29 11:31 UTC, merged