CLOUDP-70060: mongocli ops-manager|cloud-manager backups config describe
mongodb/mongocli pull request #465
Opened 2020-09-28 09:21 UTC by andreaangiolillo

## Proposed changes

_Jira ticket:_ CLOUDP-70060

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

```
./bin/mongocli om backup config list -P ops -o json
{
  "links": [
    {
      "rel": "self",
      "href": "http://localhost:8080/api/public/v1.0/groups/5f6cc16511c3aa3a90b5ec34/backupConfigs?pageNum=1\u0026itemsPerPage=100"
    }
  ],
  "results": [
    {
      "groupId": "5f6cc16511c3aa3a90b5ec34",
      "clusterId": "5f6dfb3a11c3aa3a90b66db6",
      "statusName": "INACTIVE"
    },
    {
      "groupId": "5f6cc16511c3aa3a90b5ec34",
      "clusterId": "5f719b052845cb05726a860b",
      "statusName": "STARTED",
      "storageEngineName": "WIRED_TIGER"
    },
    {
      "groupId": "5f6cc16511c3aa3a90b5ec34",
      "clusterId": "5f719b352845cb05726a86f9",
      "statusName": "STARTED",
      "storageEngineName": "WIRED_TIGER"
    }
  ],
  "totalCount": 3
}
```
```

./bin/mongocli om backup config list -P ops
PROJECT ID                 CLUSTER ID                 STATUS     STORAGE ENGINE
5f6cc16511c3aa3a90b5ec34   5f6dfb3a11c3aa3a90b66db6   INACTIVE
5f6cc16511c3aa3a90b5ec34   5f719b052845cb05726a860b   STARTED    WIRED_TIGER
5f6cc16511c3aa3a90b5ec34   5f719b352845cb05726a86f9   STARTED    WIRED_TIGER
```

2020-09-28 09:24 UTC, andreaangiolillo commented
waiting for https://github.com/mongodb/go-client-mongodb-ops-manager/pull/55

2020-09-29 08:26 UTC, gssbzn requested changes
Just one small nit

2020-09-29 08:26 UTC, gssbzn commented on internal/cli/opsmanager/backup/config/describe.go
> +		Use:     "describe [clusterID]",
[nit] brackets ([]) for optional, for mandatory the standard is less than, greater than (<>)
```suggestion
		Use:     "describe <clusterID>",
```

2020-09-29 09:41 UTC, gssbzn approved these changes
LGTM

2020-09-29 09:41 UTC, merged