CLOUDP-79634: Remove one private endpoint service for AWS or Azure in an Atlas project
mongodb/mongocli pull request #570
Opened 2021-01-14 18:40 UTC by andreaangiolillo

## Proposed changes

_Jira ticket:_ CLOUDP-79634

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

```
➜  ~/workspace/mongoCLI git:(CLOUDP-79634) ✗ ./bin/mongocli atlas privateEndpoints azure delete 6000670bb73c0024d6fd60d8
? Are you sure you want to delete: 6000670bb73c0024d6f
Private endpoint '6000670bb73c0024d6f' deleted
```
```
➜  ~/workspace/mongoCLI git:(CLOUDP-79634) ✗ ./bin/mongocli atlas privateEndpoints aws delete 600065e9ee40096395de12d5
? Are you sure you want to delete: 600065e9ee40096395de12d5 Yes
Private endpoint '600065e9ee40096395de12d5' deleted
```

2021-01-14 19:02 UTC, gssbzn requested changes
One small copy/paste issue to fix and then good to merge

2021-01-14 19:02 UTC, gssbzn commented on internal/cli/atlas/privateendpoints/azure/descriptions.go
> +	watchPrivateEndpoint     = "Watch for a specific AWS Private Endpoint to be available."
```suggestion
	watchPrivateEndpoint     = "Watch for a specific Azure Private Endpoint to be available."
```

2021-01-14 19:02 UTC, gssbzn commented on internal/cli/atlas/privateendpoints/azure/watch.go
> +	return result.Status == "WAITING_FOR_USER" || result.Status == "FAILED", nil
[q] I'm not that familiar with this API but I know for private link AWS and azure have different status, flagging this just in case

2021-01-15 09:41 UTC, gssbzn approved these changes
LGTM if LGTEVG

2021-01-15 09:42 UTC, andreaangiolillo commented
no, the e2e test has a problem. It seems that the private endpoints are shared between project. See if I can create a new organization

2021-01-15 17:20 UTC, andreaangiolillo commented
[atlas_private_endpoint_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_atlas_networking_atlas_private_endpoint_e2e_patch_ed96f83cc367158a4987431c378608ba06d14e96_6001cbc8d6d80a5b95a4ce7e_21_01_15_17_07_21)

2021-01-18 09:27 UTC, andreaangiolillo commented
@gssbzn ready for review

2021-01-18 09:33 UTC, gssbzn approved these changes
LGTM

2021-01-18 09:41 UTC, merged