CLOUDP-79639: Enable the regionalized private endpoint setting for one Atlas project;CLOUDP-79640: Disable the regionalized private endpoint setting for one Atlas project;CLOUDP-79638: Retrieve whether the regionalized private endpoint setting is enabled for one Atlas project
mongodb/mongocli pull request #581
Opened 2021-01-25 17:25 UTC by andreaangiolillo

## Proposed changes

_Jira ticket:_ CLOUDP-79638
_Jira ticket:_ CLOUDP-79639
_Jira ticket:_ CLOUDP-79640

Close detail ( T )
Cloud Services
Retrieve whether the regionalized private endpoint setting is enabled for one Atlas project

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

**Enable**
```
  ~/workspace/mongoCLI git:(CLOUDP-79639) ✗ ./bin/mongocli atlas privateendpoint regionalModes enable -o json
{
  "enabled": true
}
➜  ~/workspace/mongoCLI git:(CLOUDP-79639) ✗ ./bin/mongocli atlas privateendpoint regionalModes enable
Regionalized private endpoint setting enabled.
```
**Disable**
```
✗ ./bin/mongocli atlas privateendpoint regionalModes disable
Regionalized private endpoint setting disabled.
➜  ~/workspace/mongoCLI git:(CLOUDP-79639) ✗ ./bin/mongocli atlas privateendpoint regionalModes disable -o json
{
  "enabled": false
}
```

**Describe**
```
./bin/mongocli atlas privateendpoint regionalModes get
ENABLED
false
➜  ~/workspace/mongoCLI git:(CLOUDP-79639) ✗ ./bin/mongocli atlas privateendpoint regionalModes get -o json
{
  "enabled": false
}
```

2021-01-25 17:25 UTC, andreaangiolillo commented
waiting for https://github.com/mongodb/go-client-mongodb-atlas/pull/174

2021-01-25 17:34 UTC, gssbzn reviewed
Could we add an e2e tests to enable/disable the setting? it looks like there's no major dependency on external provider so should be doable?

2021-01-25 17:34 UTC, gssbzn commented on internal/cli/atlas/privateendpoints/regionalmodes/descriptions.go
> +	regionalMode = "Manage regionalized private endpoint setting for one Atlas project."
[nb] we usually say, "...your Atlas project..." rather than "one" but not blocking on this

2021-01-26 10:53 UTC, andreaangiolillo commented
[atlas_private_endpoint_e2e](https://evergreen.mongodb.com/task/mongocli_master_e2e_atlas_networking_atlas_private_endpoint_e2e_patch_b2945ba65268b83fdebc53b364699ce1f459b12e_600fef0cd6d80a24b87e3092_21_01_26_10_29_33)

2021-01-26 11:14 UTC, gssbzn requested changes
one super small nit

2021-01-26 11:14 UTC, gssbzn commented on e2e/atlas/private_endpoint_test.go
> +			a.Equal(false, r.Enabled)
[nit]
```suggestion
			a.False(r.Enabled)
```

2021-01-26 11:33 UTC, gssbzn approved these changes
LGTM

2021-01-26 11:39 UTC, merged